type = "text"
topic = """
    Macro sharing & development. Feel free to start threads for developing macros for specific fights, etc.

    Official DESU macros will be posted to the appropriate encounter thread and to the site.
"""
