type = "text"
topic = "Use this channel to share your macros for current and older content! Macros for fight strategies are OFFICIALLY ENDORSED by DESU! All fight spoilers allowed, but careful not to spoil fight names untagged. This channel is for macros ONLY, please keep discussion to the appropriate channels."
