type = "text"

[[messages]]
title = "1. Above all, be respectful!"
description = """
      Keep this community welcoming to everyone! This means no attacking others based on their personal identity or characteristics, no disparaging stereotypes, no harassment, and no being a generally unpleasant human being. Just generally don't be an asshole. Keep personal drama out of the server. We aren't interested.

      If a conversation is getting heated, moderators may ask for it to move to private messages or stop altogether.
      
      Similarly, please respect Discord's and FFXIV's rules in this server as well (exception: see rule 3), as well as individual channel topics & rules. If a conversation starts to stray from the topic of the channel, please make a good-faith effort to redirect it to the proper channel.

      If you're ever unsure about whether something crosses the line, please contact a mod (see info at the bottom) to ask!
"""

[[messages]]
title = "2. Use your character name"
description = """
      Please use your primary Dynamis character name as your name on this server. You may optionally add additional flair, such as your server.

      The purpose of this rule is to build community associated with the game: to be able to recognize and find players in-game in the server, and vice versa.
"""

[[messages]]
title = "3. Mods that given an unfair advantage are BANNED"
description = """
      Mods are an important part of many players' experience, especially ACT. Discussion of mods in general is allowed. However, mods that give a player an unfair advantage, such as automatic callouts, are banned in this server and should not be discussed.

      Using mods of any kind is still a violation of FFXIV's Terms of Service. Use them at your own risk, don't talk about them in-game, and do not assume players will use mods. Some players cannot use mods, others are not comfortable with the risk. Respect that.
"""

[[messages]]
title = "4. Spoiler policy"
description = """
      Current patch spoilers must be tagged throughout the server, except in channels/threads dedicated to new content. The current expansion, apart from current patch, may be talked about in general terms, but major story spoilers must be kept in dedicated threads/channels or tagged. Extreme/savage encounter names from current expac should be considered spoilers; please use EX1, EX2, etc. and P5S, P6S, etc. to refer to them.

      Content spoilers (e.g. fight mechanics) should be restricted to appropriate channels, even for older content, as some people want to be able to do older content unspoiled.

      If someone spoils inappropriately, please ask them to edit/delete their message. Ping moderators if they don't respond quickly, or if the spoiler is a very big one (e.g. the identity of the Endwalker MSQ trial bosses). Moderators may delete messages with spoilers without warning, if it's judged urgent enough.
"""

[[messages]]
title = "5. Don't argue with moderators in public"
description = """
      Moderators are volunteers working hard to keep this community a wonderful place to be. Please respect their decisions and do not argue with a mod in public. If you disagree with a moderation decision, you can discuss it in private (see info at the bottom).

      Expect to be treated harshly if you can't follow this rule.
"""

[[messages]]
title = "INFO: Contact moderators if you need"
description = """
      This isn't really a rule, just information.

      If you need non-urgent moderator help, head to <#${discord_text_channel.open-a-ticket.id}> to open a ticket. Your concerns will be kept confidential.

      If you need urgent moderator help, please do ping the <@&${data.discord_role.moderator.id}> role. We'll try to respond as quickly as possible. You can ping in a private ticket channel or out in the open.

      You are also welcome to DM mods directly, such as to discuss a moderation decision (see rule 5). If you have an issue with a moderator or admin, please DM the server owner <@680587682858270764> directly.
"""