type = "text"

[[messages]]
title = "1. Above all, be respectful!"
description = """
      Keep this community welcoming to everyone! This means no attacking others based on their personal identity or characteristics, no disparaging stereotypes, no harassment, and no being a generally unpleasant human being. Just generally don't be an asshole. Keep personal drama out of the server. We aren't interested.

      If a conversation is getting heated, moderators may ask for it to move to private messages or stop altogether.
      
      Similarly, please respect Discord's and FFXIV's rules in this server as well (exception: see rule 3), as well as individual channel topics & rules. If a conversation starts to stray from the topic of the channel, please make a good-faith effort to redirect it to the proper channel.

      If you're ever unsure about whether something crosses the line, please contact a mod (see info at the bottom) to ask!
"""

[[messages]]
title = "2. Use your character name"
description = """
      Please use your primary Dynamis character name as your name on this server. You may optionally add additional flair, such as your server.

      The purpose of this rule is to build community associated with the game: to be able to recognize and find players in-game in the server, and vice versa.
"""

[[messages]]
title = "3. Mods that given an unfair advantage are BANNED"
description = """
      Mods are an important part of many players' experience, especially ACT. Discussion of mods in general is allowed. However, mods that give a player an unfair advantage, such as automatic callouts, are banned in this server and should not be discussed.

      Using mods of any kind is still a violation of FFXIV's Terms of Service. Use them at your own risk, don't talk about them in-game, and do not assume players will use mods. Some players cannot use mods, others are not comfortable with the risk. Respect that.
"""

[[messages]]
title = "4. Spoiler policy"
description = """
      DESU intends to be a welcoming community for folks at all levels of experience, so we ask that you be cautious not to spoil other players! We are, however, conscious of how spoiler tags can get in the way of free and open discussion, and so we've updated our spoiler policy to assist with that.

      **Party Up and Static Recruitment sections**

      - Spoiler tags should be used for 2 weeks following the release of new content, except for fight-specific discussion under that fight's thread in #duties.
      - Spoiler tags are otherwise not required.

      **Community section channels**

      - MSQ spoilers should be clearly tagged in all channels except #spoilers (e.g., ShB spoiler ||Amaros are the coolest mounts||)
      
      Datamined content is still fully not permitted.

      The overall intent is to allow for raid-related discussion without worry and without being too strict, while also preventing new and returning players (or players taking a break) from missing out on on the community and fun. If you have any doubts on whether something should be tagged, ask a moderator, or spoiler it out!
"""

[[messages]]
title = "INFO: How to Use Spoilers"
description = """
      You can use \\|\\|spoiler markup\\|\\| to discuss spoilers, but it must be tagged with an appropriate warning. For instance, [HW] spoiler warns that the spoiler bar might spoil anything from Heavensward (including HW patches).

      Spoilers can be discussed openly in dedicated threads. For instance, in a thread about a specific fight, you can freely discuss that fight's mechanics. __Careful:__ The thread title and first message must not contain spoilers as they can be seen without opening the thread.

      *All* spoilers are fair game in spoiler channels, including new patch spoilers.

      Images are equally subject to the spoiler policy. When you attach an image, you can mark it as a spoiler, but you can't mark an image as a spoiler when editing a message. __Careful:__ When posting in <#${discord_text_channel.party-finder.id}>, screenshots of PF postings may need to be marked as spoilers!

      If another user breaks the spoiler policy, please ask them to correct their message. If the situation is urgent/the user is not responding, please ping <@&${data.discord_role.moderator.id}> and we will delete the message. The spoiler policy will be aggressively enforced to protect new players, but there's no further consequence unless you're posting spoilers deliberately or repeatedly.
"""

[[messages]]
title = "5. Don't argue with moderators in public"
description = """
      Moderators are volunteers working hard to keep this community a wonderful place to be. Please respect their decisions and do not argue with a mod in public. If you disagree with a moderation decision, you can discuss it in private (see info at the bottom).

      Expect to be treated harshly if you can't follow this rule.
"""

[[messages]]
title = "INFO: Contact moderators if you need"
description = """
      This isn't really a rule, just information.

      If you need non-urgent moderator help, head to <#${discord_text_channel.open-a-ticket.id}> to open a ticket. Your concerns will be kept confidential.

      If you need urgent moderator help, please do ping the <@&${data.discord_role.moderator.id}> role. We'll try to respond as quickly as possible. You can ping in a private ticket channel or out in the open.

      You are also welcome to DM mods directly, such as to discuss a moderation decision (see rule 5). If you have an issue with a moderator or admin, please DM the server owner <@680587682858270764> directly.
"""
