type = "text"

[[messages]]
title = "Welcome to DESU! 👋"
description = """
    **What is DESU?**

    DESU is a community aiming to build up the Party Finder experience on Dynamis, and to provide a wealth of resources for everyone looking to tackle any and all of the high-end combat content this game has to offer - together.
"""

[[messages]]
title = "Our main objectives:"
description = """
    1. Getting into endgame content, Savage especially, can be daunting.
    DESU wants to be a place where players who are new to all this can feel they have a safe place to ask questions and be happily welcomed into the community!

    2. Many of us came to Dynamis in hopes of building a different and more consistent Party Finder culture from the rest of NA, by taking inspiration from the best parts of each region's approach to content.
    For example, by establishing baseline conventions, standardizing names for strategies, and ditching the "clock spot dance" for macros that take your specific role into account across different fights.
    We hope this will help the entire data center focus more on what's happening, and less on arguing and trying to remember strats

    3. Especially as our DC finds its legs, finding groups can be hard.
    DESU helps folks get in touch - whether you're searching for pick-up groups, trying to get stuff unlocked, or seeking people to play with on a more regular basis.

    This is a great opportunity to get to know one another and learn from each other! Remember, the real secret of Dynamis is the power of friendship! ✨
"""

[[messages]]
title = "Getting Started"
description = """
    To get into DESU, you have to clear the door boss: <@&${data.discord_role.kupobot.id}>.
    If you haven't already registered with KupoBot on another server, or if you recently transferred, head over to #setup-instructions to get your character set up.

    Once you're registered, you can head to <#${discord_text_channel.optional-roles.id}> to select roles.
    You'll find pingable roles for specific fights, mentorship and learning roles, and more.
    If you're interested in hearing about minor updates to the server, be sure to grab the <@&${data.discord_role.tunedin.id}> role.

    From there you should be all set to head over to <#${discord_text_channel.general.id}> and say hi,
    tell us more about youself in <#${discord_text_channel.introductions.id}> if you like,
    or even jump right into <#${discord_text_channel.party-finder.id}>! 👍
"""

[[messages]]
title = "Invite Link"
description = "Use this link to invite people to the server: https://discord.gg/hVtSqdfFqX"

[[messages]]
title = "Helping Out"
description = """
    We're always looking for more folks to help out around the community. Some areas where we could use help include:

    * Promoting the community and PF on Dynamis
    * Writing guides and curating resources
    * Graphic art (emojis/some other ideas)
    * Proofreading 

    If you're interested in helping out, please drop me a line! Don't be shy!
"""
