type = "text"
topic = """
    Post events here. For access to the Raid-Helper bot, please contact staff. We're working on a better solution.

    This channel is reserved for event postings; *all* chatter must go in threads or #planning. Spoilers are **not** allowed; event listings must be appropriately tagged for spoilers or be put in #events-spoilers.
"""
